"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DepositManagerMock__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "token",
                type: "address",
            },
            {
                internalType: "address",
                name: "user",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
            },
        ],
        name: "depositERC20ForUser",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
const _bytecode = "0x608080604052346100155760af908161001a8239f35b5f80fdfe6004361015600b575f80fd5b5f3560e01c638b9e4f9314601d575f80fd5b3460755760607ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc36011260755773ffffffffffffffffffffffffffffffffffffffff6004358181160360755760243590811603607557005b5f80fdfea26469706673582212205c2e27408f7b30bc58abe96a898f9afd15b8480e1b760e64770ad38a947be2f664736f6c63430008170033";
const isSuperArgs = (xs) => xs.length > 1;
class DepositManagerMock__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.DepositManagerMock__factory = DepositManagerMock__factory;
DepositManagerMock__factory.bytecode = _bytecode;
DepositManagerMock__factory.abi = _abi;
